version: '3.7'

services:

  app:
    container_name: cga-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
    environment:
      - CHOKIDAR_USEPOLLING=true
